# application.yml
spring:
  datasource:
    url: jdbc:postgresql://pgbouncer:6432/cruxpass?preferQueryMode=simple
    username: postgres
    password: password
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 5000
      pool-name: CruxHikariPool
      data-source-properties:
        sendExtraFloatDigits: false

  jpa:
    open-in-view: false
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect

  jackson:
    serialization:
      "[INDENT_OUTPUT]": true
      
  logging:
    level:
      root: DEBUG
      "[org.hibernate.SQL]": INFO
      "[org.hibernate.type.descriptor.sql]": TRACE
jwt:
  secret-file: /run/secrets/jwt_secret


#    "[org.springframework.web]": DEBUG
#    "[org.springframework.web.servlet.DispatcherServlet]": DEBUG
#    "[org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping]": DEBUG
